# Generated by Django 5.1.7 on 2025-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='description',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='available',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('PG', 'PG'), ('Hostel', 'Hostel'), ('Apartment', 'Apartment'), ('Shared Flat', 'Shared Flat')], default='PG', max_length=20),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='review_count',
            field=models.IntegerField(default=0.0),
        ),
    ]
